language: python
dist: trusty

matrix:
    fast_finish: true
    include:
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35-sqlite
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=py36
        - python: 3.7-dev
          env:
          - PYTHON_VERSION=python3.7
          - TOXENV=py37
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=style
    allow_failures:
        - python: 3.7-dev
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=style

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip
    #- .tox

install:
  - travis_retry pip install tox


before_script:
  - pip install -U pip

script:
  # https://pypi.python.org/pypi/coverage_enable_subprocess
  - pip install coverage-enable-subprocess
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  # This env variable is passed to scaffold tests that test the tests themselves
  - export TRAVIS=true
  - tox --

after_success:
  # Update coverage information in codecov.io.
  - .tox/py35/bin/codecov
  # Dump package list so we have a log of last known good version set
  - .tox/py35/bin/pip freeze

